# Generated by Django 4.1.2 on 2022-10-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_categories_comments_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='bid',
        ),
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameModel(
            old_name='bids',
            new_name='comment',
        ),
        migrations.RenameModel(
            old_name='listings',
            new_name='listing',
        ),
    ]
