# Generated by Django 4.1.2 on 2022-10-10 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_comments_bid_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlistUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
